#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import shutil
import signal
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml
from huggingface_hub import snapshot_download


ROOT_USER = os.environ.get("BOOTSTRAP_USER", "root")
TMUX_PATTERNS = (
    re.compile(r"tmux\s+attach"),
    re.compile(r"tmux\s+new"),
    re.compile(r"attach-session"),
    re.compile(r"new-session"),
    re.compile(r"has-session"),
)


def repo_root_from_arg(value: str | None) -> Path:
    if value:
        return Path(value).resolve()
    return Path(__file__).resolve().parents[1]


def getenv_path(name: str, default: str) -> Path:
    return Path(os.environ.get(name, default)).expanduser().resolve()


def log(message: str) -> None:
    print(f"[bootstrap] {message}", flush=True)


def run(
    cmd: list[str],
    *,
    cwd: Path | None = None,
    env: dict[str, str] | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    log("$ " + " ".join(cmd))
    return subprocess.run(
        cmd,
        cwd=str(cwd) if cwd else None,
        env=env,
        check=check,
        text=True,
    )


def read_text_lines(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def load_yaml(path: Path) -> Any:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or []
    if not isinstance(data, list):
        raise ValueError(f"{path} must contain a YAML list")
    return data


def ensure_dirs(paths: list[Path]) -> None:
    for path in paths:
        path.mkdir(parents=True, exist_ok=True)


def write_if_changed(path: Path, content: str, mode: int | None = None) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    if mode is not None:
        path.chmod(mode)


def bootstrap_env(repo_root: Path) -> dict[str, Any]:
    workspace_root = getenv_path("WORKSPACE_ROOT", "/workspace")
    bootstrap_root = getenv_path("BOOTSTRAP_ROOT", str(repo_root))
    comfyui_root = getenv_path("COMFYUI_ROOT", str(workspace_root / "ComfyUI"))
    hf_home = getenv_path("HF_HOME", str(workspace_root / ".cache" / "huggingface"))
    hf_hub_cache = getenv_path("HF_HUB_CACHE", str(hf_home / "hub"))
    log_dir = getenv_path("LOG_DIR", str(workspace_root / "logs"))
    comfy_log = Path(os.environ.get("COMFYUI_LOG_FILE", str(log_dir / "comfyui.log")))
    pid_file = Path(os.environ.get("COMFYUI_PID_FILE", str(log_dir / "comfyui.pid")))
    state_dir = workspace_root / ".bootstrap-state"
    return {
        "repo_root": repo_root,
        "workspace_root": workspace_root,
        "bootstrap_root": bootstrap_root,
        "comfyui_root": comfyui_root,
        "hf_home": hf_home,
        "hf_hub_cache": hf_hub_cache,
        "log_dir": log_dir,
        "comfy_log": comfy_log,
        "pid_file": pid_file,
        "state_dir": state_dir,
        "config_dir": repo_root / "config",
        "bin_dir": repo_root / "bin",
    }


def profile_exports(env_info: dict[str, Any]) -> str:
    bootstrap_bin = env_info["bin_dir"]
    return "\n".join(
        [
            "export WORKSPACE_ROOT=\"%s\"" % env_info["workspace_root"],
            "export BOOTSTRAP_ROOT=\"%s\"" % env_info["bootstrap_root"],
            "export COMFYUI_ROOT=\"%s\"" % env_info["comfyui_root"],
            "export HF_HOME=\"%s\"" % env_info["hf_home"],
            "export HF_HUB_CACHE=\"%s\"" % env_info["hf_hub_cache"],
            "export PATH=\"%s:$PATH\"" % bootstrap_bin,
            "",
        ]
    )


def persist_profile_env(env_info: dict[str, Any]) -> None:
    profile_script = Path("/etc/profile.d/comfyui-bootstrap.sh")
    content = "# Generated by Vast.ai ComfyUI bootstrap\n" + profile_exports(env_info)
    try:
        write_if_changed(profile_script, content, 0o644)
    except PermissionError:
        log("Skipping /etc/profile.d update because permissions are insufficient")


def sanitize_rc_file(path: Path) -> None:
    if not path.exists():
        return
    original = path.read_text(encoding="utf-8").splitlines()
    filtered: list[str] = []
    changed = False
    for line in original:
        if any(pattern.search(line) for pattern in TMUX_PATTERNS):
            changed = True
            continue
        filtered.append(line)
    if changed:
        path.write_text("\n".join(filtered).rstrip() + "\n", encoding="utf-8")


def ensure_comfyui_repo(env_info: dict[str, Any]) -> None:
    target = env_info["comfyui_root"]
    repo_url = os.environ.get("COMFYUI_REPO", "https://github.com/comfyanonymous/ComfyUI.git")
    repo_ref = os.environ.get("COMFYUI_REF", "").strip()
    if (target / ".git").exists():
        run(["git", "fetch", "--all", "--tags"], cwd=target)
    elif target.exists() and any(target.iterdir()):
        log(f"ComfyUI root {target} exists and is not empty; leaving it untouched")
    else:
        ensure_dirs([target.parent])
        run(["git", "clone", repo_url, str(target)])
    if repo_ref and (target / ".git").exists():
        run(["git", "checkout", repo_ref], cwd=target)
    requirements = target / "requirements.txt"
    if requirements.exists():
        run([sys.executable, "-m", "pip", "install", "-r", str(requirements)])


def install_system_packages(env_info: dict[str, Any]) -> None:
    if os.environ.get("INSTALL_SYSTEM_PACKAGES", "1") == "0":
        log("Skipping apt packages because INSTALL_SYSTEM_PACKAGES=0")
        return
    if shutil.which("apt-get") is None:
        log("Skipping apt packages because apt-get is unavailable")
        return
    packages = read_text_lines(env_info["config_dir"] / "system-packages.txt")
    if not packages:
        return
    run(["apt-get", "update"])
    run(["apt-get", "install", "-y", "--no-install-recommends", *packages])


def install_shell(env_info: dict[str, Any]) -> None:
    home = Path(os.environ.get("BOOTSTRAP_HOME") or os.environ.get("HOME", f"/{ROOT_USER}"))
    zsh_path = shutil.which("zsh")
    if not zsh_path:
        log("zsh was not found after package installation; skipping shell switch")
        return

    oh_my_zsh_dir = home / ".oh-my-zsh"
    plugin_root = oh_my_zsh_dir / "custom" / "plugins"
    plugin_sources = {
        "zsh-autosuggestions": "https://github.com/zsh-users/zsh-autosuggestions.git",
        "zsh-syntax-highlighting": "https://github.com/zsh-users/zsh-syntax-highlighting.git",
    }
    if not oh_my_zsh_dir.exists():
        run(["git", "clone", "https://github.com/ohmyzsh/ohmyzsh.git", str(oh_my_zsh_dir)])
    ensure_dirs([plugin_root])
    for name, source in plugin_sources.items():
        destination = plugin_root / name
        if not destination.exists():
            run(["git", "clone", source, str(destination)])

    for rc_path in (home / ".bashrc", home / ".profile", home / ".zshrc"):
        try:
            sanitize_rc_file(rc_path)
        except PermissionError:
            log(f"Skipping tmux cleanup for {rc_path} because it is not writable")

    zshrc_template = (env_info["config_dir"] / "zsh" / ".zshrc").read_text(encoding="utf-8")
    zshrc = (
        zshrc_template.replace("__COMFYUI_ROOT__", str(env_info["comfyui_root"]))
        .replace("__BOOTSTRAP_ROOT__", str(env_info["bootstrap_root"]))
        .replace("__WORKSPACE_ROOT__", str(env_info["workspace_root"]))
    )
    try:
        write_if_changed(home / ".zshrc", zshrc, 0o644)
    except PermissionError:
        log(f"Skipping .zshrc install because {home} is not writable")

    if shutil.which("chsh"):
        subprocess.run(["chsh", "-s", zsh_path, ROOT_USER], check=False, text=True)
    elif shutil.which("usermod"):
        subprocess.run(["usermod", "-s", zsh_path, ROOT_USER], check=False, text=True)


def install_custom_nodes(env_info: dict[str, Any]) -> None:
    nodes = load_yaml(env_info["config_dir"] / "custom-nodes.lock.yaml")
    custom_root = env_info["comfyui_root"] / "custom_nodes"
    ensure_dirs([custom_root])
    for node in nodes:
        name = node["name"]
        repo = node["repo"]
        commit = node.get("commit")
        path = custom_root / node.get("path", name)
        if (path / ".git").exists():
            run(["git", "fetch", "--all", "--tags"], cwd=path)
        elif path.exists() and any(path.iterdir()):
            log(f"Custom node path {path} already exists and is not a git repo; skipping clone")
        else:
            run(["git", "clone", repo, str(path)])
        if commit and str(commit).lower() != "null" and (path / ".git").exists():
            run(["git", "checkout", commit], cwd=path)

        requirements = node.get("requirements")
        if requirements:
            req_path = path / requirements
            if req_path.exists():
                run([sys.executable, "-m", "pip", "install", "-r", str(req_path)])

        for install_cmd in node.get("install", []) or []:
            run(["bash", "-lc", install_cmd], cwd=path)


def sync_models(env_info: dict[str, Any]) -> None:
    models = load_yaml(env_info["config_dir"] / "models.lock.yaml")
    for model in models:
        if model.get("private") and not os.environ.get("HF_TOKEN"):
            raise RuntimeError(
                f"Model {model['name']} is marked private but HF_TOKEN is not set"
            )
        target_dir = Path(model["target_dir"])
        if not target_dir.is_absolute():
            target_dir = env_info["comfyui_root"] / target_dir
        ensure_dirs([target_dir])
        log(f"Syncing model {model['name']} into {target_dir}")
        snapshot_download(
            repo_id=model["repo_id"],
            revision=model["revision"],
            local_dir=str(target_dir),
            allow_patterns=model.get("include") or None,
            ignore_patterns=model.get("exclude") or None,
            token=os.environ.get("HF_TOKEN"),
            resume_download=True,
        )


def restore_comfy_config(env_info: dict[str, Any]) -> None:
    archive = env_info["config_dir"] / "comfyui-config.tar.zst"
    if not archive.exists():
        log(f"Skipping ComfyUI config restore because {archive.name} does not exist")
        return
    ensure_dirs([env_info["workspace_root"]])
    run(
        [
            "tar",
            "--zstd",
            "-xf",
            str(archive),
            "-C",
            str(env_info["workspace_root"]),
        ]
    )


def pid_running(pid_file: Path) -> bool:
    if not pid_file.exists():
        return False
    try:
        pid = int(pid_file.read_text(encoding="utf-8").strip())
    except ValueError:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def build_comfy_command(env_info: dict[str, Any]) -> list[str]:
    host = os.environ.get("COMFYUI_HOST", "0.0.0.0")
    port = os.environ.get("COMFYUI_PORT", "8188")
    extra_args = os.environ.get("COMFYUI_ARGS", "").strip()
    command = [sys.executable, "main.py", "--listen", host, "--port", port]
    if extra_args:
        command.extend(extra_args.split())
    return command


def start_comfy(env_info: dict[str, Any], *, tmux: bool, foreground: bool) -> None:
    comfyui_root = env_info["comfyui_root"]
    log_file = env_info["comfy_log"]
    pid_file = env_info["pid_file"]
    ensure_dirs([env_info["log_dir"]])

    if pid_running(pid_file):
        log(f"ComfyUI already running with pid from {pid_file}")
        return

    command = build_comfy_command(env_info)
    if tmux:
        if shutil.which("tmux") is None:
            raise RuntimeError("tmux is not installed")
        session = os.environ.get("COMFYUI_TMUX_SESSION", "comfyui")
        subprocess.run(["tmux", "has-session", "-t", session], check=False, text=True)
        run(
            [
                "tmux",
                "new-session",
                "-d",
                "-s",
                session,
                "cd %s && %s >> %s 2>&1"
                % (comfyui_root, " ".join(command), log_file),
            ]
        )
        return

    if foreground:
        os.chdir(comfyui_root)
        os.execvpe(command[0], command, os.environ.copy())

    with log_file.open("a", encoding="utf-8") as handle:
        process = subprocess.Popen(
            command,
            cwd=str(comfyui_root),
            stdout=handle,
            stderr=subprocess.STDOUT,
            text=True,
            start_new_session=True,
        )
    pid_file.write_text(str(process.pid), encoding="utf-8")
    log(f"ComfyUI started in background with pid {process.pid}")


def show_logs(env_info: dict[str, Any], follow: bool) -> None:
    log_file = env_info["comfy_log"]
    if not log_file.exists():
        raise RuntimeError(f"Log file not found: {log_file}")
    command = ["tail", "-n", "200", str(log_file)]
    if follow:
        command.insert(1, "-f")
    os.execvp(command[0], command)


def attach_tmux() -> None:
    session = os.environ.get("COMFYUI_TMUX_SESSION", "comfyui")
    if shutil.which("tmux") is None:
        raise RuntimeError("tmux is not installed")
    os.execvp("tmux", ["tmux", "attach", "-t", session])


def bootstrap_all(repo_root: Path) -> None:
    env_info = bootstrap_env(repo_root)
    ensure_dirs(
        [
            env_info["workspace_root"],
            env_info["bootstrap_root"],
            env_info["hf_home"],
            env_info["hf_hub_cache"],
            env_info["log_dir"],
            env_info["state_dir"],
        ]
    )
    persist_profile_env(env_info)
    install_system_packages(env_info)
    install_shell(env_info)
    ensure_comfyui_repo(env_info)
    install_custom_nodes(env_info)
    sync_models(env_info)
    restore_comfy_config(env_info)
    start_comfy(env_info, tmux=False, foreground=False)
    (env_info["state_dir"] / "bootstrap.complete").write_text("ok\n", encoding="utf-8")
    log("Bootstrap completed successfully")


def main() -> None:
    parser = argparse.ArgumentParser(description="Vast.ai ComfyUI bootstrap")
    parser.add_argument("--repo-root", default=None)
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("bootstrap")

    start_parser = subparsers.add_parser("start-comfy")
    start_parser.add_argument("--tmux", action="store_true")
    start_parser.add_argument("--foreground", action="store_true")

    logs_parser = subparsers.add_parser("logs-comfy")
    logs_parser.add_argument("--follow", action="store_true")

    subparsers.add_parser("attach-comfy")
    subparsers.add_parser("install-shell")
    subparsers.add_parser("install-nodes")
    subparsers.add_parser("sync-models")
    subparsers.add_parser("restore-config")

    args = parser.parse_args()
    repo_root = repo_root_from_arg(args.repo_root)
    env_info = bootstrap_env(repo_root)

    if args.command == "bootstrap":
        bootstrap_all(repo_root)
    elif args.command == "start-comfy":
        start_comfy(env_info, tmux=args.tmux, foreground=args.foreground)
    elif args.command == "logs-comfy":
        show_logs(env_info, follow=args.follow)
    elif args.command == "attach-comfy":
        attach_tmux()
    elif args.command == "install-shell":
        install_shell(env_info)
    elif args.command == "install-nodes":
        install_custom_nodes(env_info)
    elif args.command == "sync-models":
        sync_models(env_info)
    elif args.command == "restore-config":
        restore_comfy_config(env_info)
    else:
        raise SystemExit(f"Unknown command: {args.command}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        os.kill(os.getpid(), signal.SIGINT)
