#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from huggingface_hub import HfApi


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-")


@dataclass
class UploadEntry:
    name: str
    local_path: str
    path_in_repo: str
    lock_target_dir: str = "."
    private: bool = True
    revision: str = "main"


def load_entries(path: Path) -> list[UploadEntry]:
    with path.open("r", encoding="utf-8") as handle:
        raw = yaml.safe_load(handle) or []
    if not isinstance(raw, list):
        raise ValueError(f"{path} must contain a YAML list")

    entries: list[UploadEntry] = []
    for item in raw:
        entries.append(
            UploadEntry(
                name=item["name"],
                local_path=item["local_path"],
                path_in_repo=item.get("path_in_repo") or item["local_path"],
                lock_target_dir=item.get("lock_target_dir", "."),
                private=bool(item.get("private", True)),
                revision=item.get("revision", "main"),
            )
        )
    return entries


def generate_lock(entries: list[UploadEntry], repo_id: str) -> list[dict[str, Any]]:
    output: list[dict[str, Any]] = []
    for entry in entries:
        output.append(
            {
                "name": entry.name,
                "repo_id": repo_id,
                "revision": entry.revision,
                "target_dir": entry.lock_target_dir,
                "include": [entry.path_in_repo],
                "exclude": [],
                "private": entry.private,
            }
        )
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description="Upload private ComfyUI models to Hugging Face")
    parser.add_argument("--config", default="config/private-models.upload.yaml")
    parser.add_argument("--comfyui-root", default=os.environ.get("COMFYUI_ROOT", "/workspace/ComfyUI"))
    parser.add_argument("--namespace", default=os.environ.get("HF_NAMESPACE"))
    parser.add_argument("--repo-name", default=os.environ.get("HF_PRIVATE_REPO", "comfyui-private-models"))
    parser.add_argument("--token", default=os.environ.get("HF_TOKEN"))
    parser.add_argument("--write-lock", default="config/private-models.generated.lock.yaml")
    parser.add_argument("--skip-upload", action="store_true")
    args = parser.parse_args()

    if not args.namespace:
        raise SystemExit("HF namespace is required. Set HF_NAMESPACE or pass --namespace.")

    config_path = Path(args.config).resolve()
    comfyui_root = Path(args.comfyui_root).resolve()
    entries = load_entries(config_path)
    repo_id = f"{args.namespace}/{args.repo_name}"
    lock_entries = generate_lock(entries, repo_id)

    write_lock_path = Path(args.write_lock).resolve()
    write_lock_path.parent.mkdir(parents=True, exist_ok=True)
    write_lock_path.write_text(
        "# Generated by hf_private_uploader.py\n" + yaml.safe_dump(lock_entries, sort_keys=False),
        encoding="utf-8",
    )

    if args.skip_upload:
        print(f"Wrote lock file to {write_lock_path}")
        return

    api = HfApi(token=args.token) if args.token else HfApi()
    api.create_repo(repo_id=repo_id, repo_type="model", private=True, exist_ok=True)
    for entry in entries:
        local_path = Path(entry.local_path)
        if not local_path.is_absolute():
            local_path = comfyui_root / local_path
        if not local_path.exists():
            raise SystemExit(f"Local path does not exist: {local_path}")

        api.upload_file(
            path_or_fileobj=str(local_path),
            path_in_repo=entry.path_in_repo,
            repo_id=repo_id,
            repo_type="model",
            revision=entry.revision,
            commit_message=f"Upload {entry.name}",
        )
        print(f"Uploaded {local_path} -> {repo_id}/{entry.path_in_repo}")

    print(f"Wrote lock file to {write_lock_path}")


if __name__ == "__main__":
    main()
